SELECT CC_REC_START_DATE + 10 from CALL_CENTER LIMIT ALL;
 
SELECT CC_REC_START_DATE + interval '10 days' from CALL_CENTER;
 
insert into UTF8_TEST values ("abcd", "abcd", 4); --SAMPLE_STRING

INSERT INTO UTF8_TEST(BASE_LANGUAGE, SAMPLE_STRING, DISTRIBUTION_COLUMN) values( 'abcd' , 'euro euro', 4);

INSERT INTO UTF8_TEST(BASE_LANGUAGE, SAMPLE_STRING, DISTRIBUTION_COLUMN) values( 'abcd' , 'euro euro', 4);

INSERT INTO WEB_PAGE values ( 10,cast('id' as varchar(10)), now() , CURRENT_DATE ,10,10,'y',10,'y', substr('wearehere', 4), 10,10,10,10);

SET FACTREL_SIZE_THRESHOLD = 25000000;
SELECT NUMERIC(WR_RETURN_AMT) FROM WEB_RETURNS;

SELECT NUMERIC(WR_RETURN_AMT,7,2) FROM WEB_RETURNS;

SELECT (WR_RETURN_AMT)::NUMERIC(7,2) FROM WEB_RETURNS;
